print('Step 1 merge raw data')
print('Step 2 pre process merged data')
print('Step 3 separate merged data into files')
print('Step 3 specific to branch feature_x, perform series to supervised to the data sets')
print('Step 4 pre process each file')